service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

custom:
  stage: ${opt:stage, 'dev'}

functions:
  upload:
    handler: src/upload.run
    events:
      - s3:
          bucket: afa-${self:custom.stage}-pop-rs
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .zip
